---
# Main playbook

- name: Setup GlusterFS Persistent Storage Cluster
  hosts: load-balancers
  become: true
  roles:
    - common
    - glusterfs-persistent-storage
  tags: [glusterfs, common]



- name: Setup Swarm Cluster
  hosts: load-balancers
  become: true
  roles:
    - docker-swarm
  tags: swarm



- name: Deploy Container Worklooads
  hosts: lbserver1
  become: true
  roles:
    - pihole-dns
    - nginx-load-balancer
  tags: containers