- name: Update repositories cache and install packages
  apt:
    name: 
      - net-tools
      - lshw
      - ufw
      - cifs-utils
      - psmisc
      - resolvconf
      - python3-pip
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes 
