- name: Enable UFW and deny all by default
  ufw:
    state: enabled
    policy: allow
  tags: ufw

- name: Set logging
  ufw:
    logging: 'on'
  tags: ufw

- ufw:
    rule: allow
    name: OpenSSH
  tags: ufw

# swarm ports

- name: Open NGINX ports
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80' 
    - '443'
  tags: ufw
   
- name: Allow port range 8079-8090 (App Range)
  ufw:
    rule: allow
    port: 8079:8080
    proto: tcp
  tags: ufw

- name: Open Swarm Ports TCP
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '4789' 
    - '7946'
    - '4097' #container-swarm-network
    - '2377'
  tags: ufw

- name: Open Swarm Ports UDP
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items:
    - '4789' 
    - '7946'
    - '4097' #container-swarm-network
    - '2377'
  tags: ufw
