---
- name: Install GlusterFS packages
  ansible.builtin.package:
    name: "{{ glusterfs_packages }}"
    state: present
  become: true

- name: Ensure GlusterFS service is running
  ansible.builtin.service:
    name: glusterd
    state: started
    enabled: true
  become: true
